### ISSUE TITLE
Burning LED in photocoupler is probably not the issue

### ISSUE THREAD

**Issue by ChaoticRoman** [mgravell/pigrostat#1]
> If I had to guess (I'm speculating here), I'm burning out the LED on the photocoupler, and they are connecting the power through COM and NC, meaning that if the LED fails: it will be forever on).

This is very unlikely if there is proper serial resistance with the LED. LED can blink "almost forever", say 10 years minimum, if never overloaded. 

Most probably they use poor quality relays, changing these should do the trick.

**Comment by mgravell** [comment]
I did say it was speculation ;p I'll change that... and I'm feeling more than a little observed :)

**Comment by mgravell** [comment]
changing the relays on off-the-shelf devices seems a bad solution to me; I'm happy to just send them back for a refund if they're going to ruin the product with that choice

ultimately, a hygrostat, thermostat, etc *has one freaking job* - in two parts:

1. measure the environment
2. turn the power on/off based on 1

if it can't reliably do "2", the product is defective

**Comment by ChaoticRoman** [comment]
I agree :)
